baseURL: https://karolinagroszewska.github.io/
languageCode: "en-us"
title: "Kari Groszewska"
theme: "hugo-profile"


Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "Kari Groszewska"
  description: Student/Developer
  theme:
    disableThemeToggle: true
    defaultTheme: "dark"
  
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Kari!"
    subtitle: "I am a developer, leader, and student"
    content: "Current junior at Vanderbilt studying Computer Science and Economics. Passionate about projects that make lives easier and events that break through barriers to tech."
    image: /images/me.jpg
    button:
      enable: true
      name: "Resume"
      url: "Resume_KarolinaGroszewska.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/KarolinaGroszewska"
        - icon: fab fa-linkedin
          url: "https://www.linkedin.com/in/karolina-groszewska/"
  about:
    enable: true
    title: "Recent Skills"
    image: "/images/me.png"
    content: |-
      I have 5+ years of development experience on a myriad of projects and for multiple clients. I make sure every project I work on has the ability to make the world a slightly better place.
    skills:
      enable: true
      items:
        - "React Native [Atendi]"
        - "Unity [BBSC]"
        - "Angular [Team AiR]"
        - "Java [Team AiR]"
        - "React [Intern Project]"
        - "Flask [Intern Project]"
  experience:
    enable: true
    items:
      - job: "Application Development Intern"
        company: "Vanguard"
        date: "Jun 2022 - Present"
        content: "Throughout my internship I have been a full-stack developer for Personal Advisor Services, working in Java and Angular on improving Client Onboarding Services. I am currently completing a 2-week internship extension based on business need and performance."

      - job: "Teaching Assistant"
        company: "VUSE"
        date: "August 2021 - Present"
        content: "I am an undergraduate teaching assistant for EECE 2123 - Digital Systems, which is an introductory Electrical Engineering course for Computer Science majors. I am responsible for hosting office hours, assisting students in completing assignments, devising or updating grading rubrics, and grading assignments and examinations."

      - job: "Undergraduate Research Assistant"
        company: "ISIS"
        date: "August 2021 - May 2022"
        content: "I worked on an open-source application called Improving Neighbourhood Safety Through Open Data Collection, which is a project that aims to improve the safety of neighbourhoods in the city of Nashville. I worked on the frontend written Ionic React and the MongoDB database to move the application from development to alpha."
      
      - job: "Software Engineering Intern"
        company: "Normandy"
        date: "June 2020 - August 2021"
        content: "I was a summer 2020 and 2021 Intern at Normandy Design Build Remodelling, a local renovation company. I helped improve the efficieny of the company of COVID-19 protocols for hundreds of active construction sites, and modernized their builing code download process."
      
  education:
      enable: true
      #index: true
      items:
        - title: "TBA"
          school:
            name: "TBA"
          date: "2020 - 2024"
          GPA: "3.44 out of 4.0"
          content: |-
            I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
            - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
            - Face mask detection using a single convolutional neural network.
            Extracurricular Activities
              - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
              - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.

        - title: "High School"
          school:
            name: "TBA"
            url: "https://example.org"
          GPA: "TBA"
          date: "2016 - 2020"
  leadership:
    enable: true
    items:
      - title: TBA
        content: TBA.
        url: https://example.com
      - title: TBA
        content: TBA
      - title: TBA
        content: TBA
        url: "https://example.com"

  projects:
    enable: true
    items:
      - title: TBA
        content: TBA
        image: /images/projects/profile.png
        featured:
          name: TBA
          link: "https://example.com"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
