baseURL: https://karolinagroszewska.github.io/
languageCode: "en-us"
title: "Kari Groszewska"
theme: "hugo-profile"


Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "Kari Groszewska"
  description: Student/Developer
  theme:
    disableThemeToggle: true
    defaultTheme: "dark"
  
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Kari!"
    subtitle: "I am a software developer, leader, and student"
    content: "As a current junior at Vanderbilt studying Computer Science and Economics, I am passionate about projects that make lives easier and events that break through barriers to tech."
    image: /images/me.jpg
    button:
      enable: true
      name: "Resume"
      url: "https://github.com/KarolinaGroszewska/KarolinaGroszewska.github.io/raw/main/Resume_KarolinaGroszewska.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/KarolinaGroszewska"
        - icon: fab fa-linkedin
          url: "https://www.linkedin.com/in/karolina-groszewska/"
  about:
    enable: true
    title: "Recent Skills"
    image: "/images/me.png"
    content: |-
      I have 6+ years of development experience on a myriad of projects and for multiple clients. I make sure every project I work on has the ability to make the world a slightly better place, and enjoy working with others to make things happen, Having recently reignitied my passion for mobile development, I give every new project my all.
    skills:
      enable: true
      items:
        - "Swift [Fingertip]"
        - "SwiftUI [Fingertip]"
        - "XCTest [Fingertip]"
        - "Unity [BBSC]"
        - "Angular [Team AiR]"
        - "Java [Team AiR]"
        - "React [Intern Project]"
        - "Flask [Intern Project]"
  experience:
    enable: true
    items:
      - job: "TBA"
        company: "TBA"
        date: "May 2023 - Present"
        content: "I will be talking through my recruitment season and releasing my 2023 summer internship location soon!"
      - job: "Application Development Intern"
        company: "Vanguard"
        date: "Jun 2022 - Present"
        content: "Throughout my internship I was been a full-stack developer for Personal Advisor Services as a part of team AiR, working in Java and Angular on full-stack improvements to Client Onboarding Services. I also completed a 2-week internship extension based on business need and my performance, where I completed additional user stories ahead of bringing our product to launch."

      - job: "Teaching Assistant"
        company: "VUSE"
        date: "August 2021 - Present"
        content: "Third-semester undergraduate teaching assistant for EECE 2123 - Digital Systems, which is an introductory Electrical Engineering course for Computer Science, Computer Engineering, and Electrical Engineering majors. I am responsible for hosting office hours, assisting students in completing assignments, devising or updating grading rubrics, and grading assignments and examinations."

      - job: "Undergraduate Research Assistant"
        company: "ISIS"
        date: "August 2021 - May 2022"
        content: "I worked on an open-source application, Improving Neighbourhood Safety Through Open Data Collection, which aims to increase access to community-driven safety efforts in the city of Nashville. I worked on the frontend, written Ionic React and the MongoDB database to move this NSF funded project from development to the alpha stage."
      
      - job: "Software Engineering Intern"
        company: "Normandy"
        date: "June 2020 - August 2021"
        content: "I was a summer 2020 and 2021 Intern at Normandy Design Build Remodelling, a local renovation company. I helped improve the efficieny of the company of COVID-19 protocols for hundreds of active construction sites, and modernized their builing code download process."
      
  education:
      enable: true
      #index: true
      items:
        - title: "BSc in Computer Science, Economics"
          school:
            name: "Vanderbilt University"
          date: "2020 - 2024"
          GPA: "3.46 out of 4.0"
          content: |-
            National Merit Scholar at Vanderbilt majoring in Computer Science and Economics and minoring in Spanish

        - title: "High School"
          school:
            name: "John Hersey High School"
          GPA: "4.77 out of 4.0"
          date: "2016 - 2020"
          content: |-
            Valedictorian, Computer Science Award Winner. Co-Founder of Techettes, an organization encouraging women to pursue opportunities in Computer Science. Founder of KariCode LLC, created to promote outreach of specialized library resources for high schools across the United States. Co-captain of the Debate and Model United Nations Teams.
  leadership:
    enable: true
    items:
      - title: "VandyHacks - Senior Advisor, Former President"
        content: VandyHacks is the oldest Computer Science organization at Vanderbilt that hosts an annual hackathon for students, runs a spring mentorship program, and provides learning opportunities and a community year-round. As a Senior Advisor, I am responsible for mentoring the Presidents, Directors, and Members whilst guiding them to create successful events.
        url: https://vandyhacks.org/
      - title: "Women in Computing - Grace Hopper Coordinator"
        content: Women in Computing focuses on creating a hub for students interested in pursuing tech-related ventures. This year, I am helping organize scholarships for members of the Vanderbilt community to attend the Grace Hopper Conference. I have organized and spoken at events including career nights, resume review sessions, and career panels. 
      - title: "V:Pog - Recruitment Chair"
        content: As the founding VP and current recruitment chair, I focus on finding talent for this new organization and teaching technical skills to new members. I have led a workshop on basic GitHub skills and developed functionality for our game, Baby Bear Summer Camp.

  projects:
    enable: true
    items:
    - title: Fingertip
        content: |-
          SwiftUI and XCTest. Fingertip is an iOS and watchOS passion project which allows for accountable habit tracking with time-blocking, analytics-based updates, and connection-based accountability. 
      - title: Atendi
        content: |-
          React Native. Atendi is a mobile application I have begun developing with my friends for StudioV, a women's workout community. The goal of the application is to improve attendance tracking by sending location-based push notifications to registered members.
      - title: SpotifyMatched
        content: React, Flask, PostgreSQL. Web application allowing Vanguard crew to find other users with similar music tastes. Uses the Spotify API to find similar artists and tracks and calculates a match percentage. I spearheaded the development of the React frontend and work extensively on testing and connections to the Flask backend.
      - title: Baby Bear Summer Camp
        content: Unity. A strategic world builder and management simulator centered around creating a welcoming camp for young bears, created by V:Pog during our first year as an organization.
        links:
          - icon: fab fa-github
            url: https://github.com/KarolinaGroszewska/BabyBearSummerCamp
      - title: Soba
        content: React, MongoDB. Social platform that attempts to match students with dormitories based on their interests and currently considered roommates. Uses current user-generated housing statistics to determine whether students have access to a housing option through a percentage based-system, shows the amenities, and posts current and past resident reviews. This project won second-place in the full-stack development category at UA Innovate.
        links:
          - icon: fab fa-github
            url: https://github.com/kyleburgess2025/soba
      - title: SAC Sign-In
        content: Swift, Firebase. Created for the Sexual Assault Center in Nashville, this iPad-native application logs incoming patient information, and then stores that information in secure servers for the staff to access. Started as a part of the Vanderbilt University's Summer VandyHacks 2020.
      - title: Brewed Awakening 
        content: Swift, CoreData. A point-of-sales system for my high school's coffee shop, which is run by the Career and Life Skills department for students with disabilities. A more disability friendly version of Square with larger display boxes, displaying exact change in cash with images of coins and bank notes, and management tools to facilitate the baristas' and other staff interactions with the app.

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: karolina.groszewska@gmail.com
    btnName: Email Me!

  footer:
    recentPosts: true
